disabled_rules:
  - trailing_whitespace
  - line_length
  - function_parameter_count
  - variable_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - R.generated.swift
  - Tests
included:
  - ../OCExtensions/Classes
line_length:
  - 170
  - 200
